# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ae85607a24aa71b34f54fbb3bdf50e08eca24491dd7f58010c271e1d12e59b8b57ef119405f90d19e927b62fe0ac5ffbe0936a387430242ca89b809f359151ae

test:
  secret_key_base: 5b64e6355a2dd47d9f4881dc47c3b46ca304b078621e23091f67b1516a4cff470501ce5fa012073c38ff459ebf6f724f3fe0bd81038960fbbcac25c152b2fd69

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
